<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            // Skip ID 1 as it's empty in the CSV
            ['id' => 2, 'parent_id' => null, 'name' => 'Automobile', 'code' => 'automobile', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 3, 'parent_id' => null, 'name' => 'Entertainment', 'code' => 'entertainment', 'description' => null, 'icon' => 'fas fa-film', 'color' => '#e83e8c'],
            ['id' => 4, 'parent_id' => null, 'name' => 'Family', 'code' => 'family', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 5, 'parent_id' => null, 'name' => 'Food', 'code' => 'food', 'description' => null, 'icon' => 'fas fa-utensils', 'color' => '#fd7e14'],
            ['id' => 6, 'parent_id' => null, 'name' => 'Health Care', 'code' => 'health_care', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 7, 'parent_id' => null, 'name' => 'Home Office', 'code' => 'home_office', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 8, 'parent_id' => null, 'name' => 'Household', 'code' => 'household', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 9, 'parent_id' => null, 'name' => 'Insurance', 'code' => 'insurance', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 10, 'parent_id' => null, 'name' => 'Investment', 'code' => 'investment', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 11, 'parent_id' => null, 'name' => 'Loans', 'code' => 'loans', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 12, 'parent_id' => null, 'name' => 'Other', 'code' => 'other', 'description' => null, 'icon' => 'fas fa-question-circle', 'color' => '#6c757d'],
            ['id' => 13, 'parent_id' => null, 'name' => 'Personal', 'code' => 'personal', 'description' => null, 'icon' => 'fas fa-user', 'color' => '#6f42c1'],
            ['id' => 14, 'parent_id' => null, 'name' => 'Tax', 'code' => 'tax', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 15, 'parent_id' => null, 'name' => 'Travel', 'code' => 'travel', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 16, 'parent_id' => null, 'name' => 'Utilities', 'code' => 'utilities', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 17, 'parent_id' => null, 'name' => 'Vacation', 'code' => 'vacation', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 18, 'parent_id' => 2, 'name' => 'AAA or Road Services', 'code' => 'aaa_or_road_services', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 19, 'parent_id' => 2, 'name' => 'Fuel', 'code' => 'fuel', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 20, 'parent_id' => 2, 'name' => 'Lease', 'code' => 'lease', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 21, 'parent_id' => 2, 'name' => 'Maintenance', 'code' => 'maintenance', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 22, 'parent_id' => 2, 'name' => 'Mileage', 'code' => 'mileage', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 23, 'parent_id' => 2, 'name' => 'Registration', 'code' => 'registration', 'description' => null, 'icon' => 'fas fa-car', 'color' => '#795548'],
            ['id' => 24, 'parent_id' => 3, 'name' => 'Movie', 'code' => 'movie', 'description' => null, 'icon' => 'fas fa-film', 'color' => '#e83e8c'],
            ['id' => 25, 'parent_id' => 3, 'name' => 'Party', 'code' => 'party', 'description' => null, 'icon' => 'fas fa-film', 'color' => '#e83e8c'],
            ['id' => 26, 'parent_id' => 3, 'name' => 'Subscription', 'code' => 'subscription', 'description' => null, 'icon' => 'fas fa-film', 'color' => '#e83e8c'],
            ['id' => 27, 'parent_id' => 4, 'name' => 'Child Care', 'code' => 'child_care', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 28, 'parent_id' => 4, 'name' => 'Child Education', 'code' => 'child_education', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 29, 'parent_id' => 4, 'name' => 'Toy', 'code' => 'toy', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 30, 'parent_id' => 5, 'name' => 'Groceries', 'code' => 'groceries', 'description' => null, 'icon' => 'fas fa-utensils', 'color' => '#fd7e14'],
            ['id' => 31, 'parent_id' => 5, 'name' => 'Order Online', 'code' => 'order_online', 'description' => null, 'icon' => 'fas fa-utensils', 'color' => '#fd7e14'],
            ['id' => 32, 'parent_id' => 5, 'name' => 'Restaurant', 'code' => 'restaurant', 'description' => null, 'icon' => 'fas fa-utensils', 'color' => '#fd7e14'],
            ['id' => 33, 'parent_id' => 5, 'name' => 'Snack', 'code' => 'snack', 'description' => null, 'icon' => 'fas fa-utensils', 'color' => '#fd7e14'],
            ['id' => 34, 'parent_id' => 6, 'name' => 'Dental', 'code' => 'dental', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 35, 'parent_id' => 6, 'name' => 'Eye Care', 'code' => 'eye_care', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 36, 'parent_id' => 6, 'name' => 'Health Insurance', 'code' => 'health_insurance', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 37, 'parent_id' => 6, 'name' => 'Medical', 'code' => 'medical', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 38, 'parent_id' => 6, 'name' => 'Nutrition', 'code' => 'nutrition', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 39, 'parent_id' => 6, 'name' => 'Prescription', 'code' => 'prescription', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 40, 'parent_id' => 7, 'name' => 'Computer', 'code' => 'computer', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 41, 'parent_id' => 7, 'name' => 'Electronics', 'code' => 'electronics', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 42, 'parent_id' => 7, 'name' => 'Office Furniture', 'code' => 'office_furniture', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 43, 'parent_id' => 7, 'name' => 'Office Supply', 'code' => 'office_supply', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 44, 'parent_id' => 7, 'name' => 'Stationery', 'code' => 'stationery', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 45, 'parent_id' => 8, 'name' => 'Appliance', 'code' => 'appliance', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 46, 'parent_id' => 8, 'name' => 'Consumables', 'code' => 'consumables', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 47, 'parent_id' => 8, 'name' => 'Home Maintenance', 'code' => 'home_maintenance', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 48, 'parent_id' => 8, 'name' => 'Homeowner Fees', 'code' => 'homeowner_fees', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 49, 'parent_id' => 8, 'name' => 'Household Tools', 'code' => 'household_tools', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 50, 'parent_id' => 8, 'name' => 'Miscellaneous Household Items', 'code' => 'miscellaneous_household_items', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 51, 'parent_id' => 8, 'name' => 'Postage', 'code' => 'postage', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 52, 'parent_id' => 8, 'name' => 'Rent', 'code' => 'rent', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 53, 'parent_id' => 9, 'name' => 'Auto', 'code' => 'auto', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 54, 'parent_id' => 9, 'name' => 'Health', 'code' => 'health', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 55, 'parent_id' => 9, 'name' => 'Home', 'code' => 'home', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 56, 'parent_id' => 9, 'name' => 'Life', 'code' => 'life', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 57, 'parent_id' => 10, 'name' => 'Mutual Fund', 'code' => 'mutual_fund', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 58, 'parent_id' => 10, 'name' => 'NPS', 'code' => 'nps', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 59, 'parent_id' => 10, 'name' => 'PPF', 'code' => 'ppf', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 60, 'parent_id' => 10, 'name' => 'SSY', 'code' => 'ssy', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 61, 'parent_id' => 11, 'name' => 'Home Equity', 'code' => 'home_equity', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 62, 'parent_id' => 11, 'name' => 'Mortgage', 'code' => 'mortgage', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 63, 'parent_id' => 11, 'name' => 'Student', 'code' => 'student', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 64, 'parent_id' => 13, 'name' => 'Clothing', 'code' => 'clothing', 'description' => null, 'icon' => 'fas fa-user', 'color' => '#6f42c1'],
            ['id' => 65, 'parent_id' => 13, 'name' => 'Donation', 'code' => 'donation', 'description' => null, 'icon' => 'fas fa-user', 'color' => '#6f42c1'],
            ['id' => 66, 'parent_id' => 13, 'name' => 'Gift', 'code' => 'gift', 'description' => null, 'icon' => 'fas fa-user', 'color' => '#6f42c1'],
            ['id' => 67, 'parent_id' => 13, 'name' => 'Personal Care', 'code' => 'personal_care', 'description' => null, 'icon' => 'fas fa-user', 'color' => '#6f42c1'],
            ['id' => 68, 'parent_id' => 14, 'name' => 'Property Tax', 'code' => 'property_tax', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 69, 'parent_id' => 15, 'name' => 'Airplane', 'code' => 'airplane', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 70, 'parent_id' => 15, 'name' => 'Bus', 'code' => 'bus', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 71, 'parent_id' => 15, 'name' => 'Car Rental', 'code' => 'car_rental', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 72, 'parent_id' => 15, 'name' => 'Hotel', 'code' => 'hotel', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 73, 'parent_id' => 15, 'name' => 'Taxi', 'code' => 'taxi', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 74, 'parent_id' => 15, 'name' => 'Train', 'code' => 'train', 'description' => null, 'icon' => 'fas fa-plane', 'color' => '#6610f2'],
            ['id' => 75, 'parent_id' => 16, 'name' => 'Cable TV', 'code' => 'cable_tv', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 76, 'parent_id' => 16, 'name' => 'Electric', 'code' => 'electric', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 77, 'parent_id' => 16, 'name' => 'Garbage', 'code' => 'garbage', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 78, 'parent_id' => 16, 'name' => 'Gas', 'code' => 'gas', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 79, 'parent_id' => 16, 'name' => 'Internet', 'code' => 'internet', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 80, 'parent_id' => 16, 'name' => 'Telephone', 'code' => 'telephone', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 81, 'parent_id' => 16, 'name' => 'Water', 'code' => 'water', 'description' => null, 'icon' => 'fas fa-bolt', 'color' => '#ffc107'],
            ['id' => 82, 'parent_id' => 17, 'name' => 'Misc', 'code' => 'misc', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 83, 'parent_id' => 17, 'name' => 'Other Transportation', 'code' => 'other_transportation', 'description' => null, 'icon' => 'fas fa-folder', 'color' => '#6c757d'],
            ['id' => 84, 'parent_id' => 90, 'name' => 'Salary', 'code' => 'salary', 'description' => 'Monthly salary income', 'icon' => 'fas fa-money-bill-wave', 'color' => '#28a745'],
            ['id' => 85, 'parent_id' => 90, 'name' => 'Freelance', 'code' => 'freelance', 'description' => 'Freelance work income', 'icon' => 'fas fa-laptop', 'color' => '#17a2b8'],
            ['id' => 86, 'parent_id' => 90, 'name' => 'Investment Returns', 'code' => 'investment_returns', 'description' => 'Returns from investments', 'icon' => 'fas fa-chart-line', 'color' => '#ffc107'],
            ['id' => 87, 'parent_id' => 90, 'name' => 'Business Income', 'code' => 'business_income', 'description' => 'Income from business activities', 'icon' => 'fas fa-briefcase', 'color' => '#6f42c1'],
            ['id' => 88, 'parent_id' => 90, 'name' => 'Rental Income', 'code' => 'rental_income', 'description' => 'Income from property rental', 'icon' => 'fas fa-home', 'color' => '#fd7e14'],
            ['id' => 89, 'parent_id' => 90, 'name' => 'Interest', 'code' => 'interest', 'description' => 'Bank interest and dividends', 'icon' => 'fas fa-percentage', 'color' => '#20c997'],
            ['id' => 90, 'parent_id' => null, 'name' => 'Income', 'code' => 'income', 'description' => 'All income sources and earnings', 'icon' => 'fas fa-arrow-up', 'color' => '#28a745'],
            ['id' => 92, 'parent_id' => 2, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 93, 'parent_id' => 3, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 94, 'parent_id' => 4, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 95, 'parent_id' => 5, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 96, 'parent_id' => 7, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 97, 'parent_id' => 8, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 98, 'parent_id' => 11, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 99, 'parent_id' => 11, 'name' => 'Auto', 'code' => 'AUTO', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 100, 'parent_id' => 12, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 101, 'parent_id' => 13, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 102, 'parent_id' => 17, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 103, 'parent_id' => 90, 'name' => 'Initial Balance', 'code' => 'INITIAL_BALANCE', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 104, 'parent_id' => 90, 'name' => 'Cashback', 'code' => 'CASHBACK', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 105, 'parent_id' => 90, 'name' => 'Equities', 'code' => 'EQUITIES', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 106, 'parent_id' => 90, 'name' => 'Rents and royalties', 'code' => 'RENTS_AND_ROYALTIES', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 107, 'parent_id' => 90, 'name' => 'Personal Savings', 'code' => 'PERSONAL_SAVINGS', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 108, 'parent_id' => 90, 'name' => 'Other', 'code' => 'OTHER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 109, 'parent_id' => 90, 'name' => 'Snack', 'code' => 'SNACK', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 110, 'parent_id' => 90, 'name' => 'Account Transfer', 'code' => 'ACCOUNT_TRANSFER', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 111, 'parent_id' => null, 'name' => 'Loan', 'code' => 'loan', 'description' => null, 'icon' => null, 'color' => null],
            ['id' => 91, 'parent_id' => null, 'name' => 'Account Transfer', 'code' => 'ACCOUNT_TRANSFER', 'description' => 'Transfers between accounts', 'icon' => 'fas fa-exchange-alt', 'color' => '#6c757d'],
           ];

        DB::table('categories')->insert($categories);
    }
}
